### ISSUE TITLE
Documentation "tags" are currently not themed

### ISSUE THREAD

**Issue by laceysanderson** [TripalCultivate/docs#1]
When you look at the documentation, there are large blank spots between the header and the first bit of content as shown in the following screenshot:
![Screenshot 2023-12-12 at 12 20 41 PM](https://github.com/TripalCultivate/docs/assets/1566301/a6764c6d-6c2b-4d48-9c23-0ca6c149646d)

When you look closer, there is actually white text there that indicates a badge. The Badge is specified in the head matter for the page as a "tag". Currently this is not theme'd appropriately.
![Screenshot 2023-12-12 at 12 18 03 PM](https://github.com/TripalCultivate/docs/assets/1566301/3a77d65b-08f7-4075-8118-a8db356e75a6)
![Screenshot 2023-12-12 at 12 18 45 PM](https://github.com/TripalCultivate/docs/assets/1566301/42920cab-4b33-4f08-905a-126750ebee00)
![Screenshot 2023-12-12 at 12 19 56 PM](https://github.com/TripalCultivate/docs/assets/1566301/7b8b2c0c-cce0-4568-91b5-b57d67d5c27a)

**Comment by carolyncaron** [comment]
Thanks Lacey! This has now been addressed in commit [2a1f062](https://github.com/TripalCultivate/docs/commit/2a1f062a276f196ad1c2a9e5d7233d274223a62c)
