### ISSUE TITLE
Germplasm Accession Documentation

### ISSUE THREAD

**Issue by laceysanderson** [TripalCultivate/docs#2]
As part of reviewing https://github.com/TripalCultivate/TripalCultivate-Germplasm/pull/6, I looked at the associated documentation hosted here: https://tripalcultivate.github.io/docs/docs/curation/germplasm-data. 

## My Thoughts / Suggestions:

It would be nice to have a screenshot of the importer form on this page. I would personally put it in the right margin like shown in this mock-up. 
![image_suggestion](https://github.com/TripalCultivate/docs/assets/1566301/1d95b407-d0e2-4b5f-9fd8-2200bef62aca)
Note: the CSS used to do the mock-up are the follows with the element being placed above the genus section.
```css
element {
  width: 300px;
  height: 300px;
  background-color: aquamarine;
  float: right;
  margin-left: 50px;
}
```

The first column could be more specific by saying "the official name of this accession (e.g. CDC Greenstar). If there are multiple names for this accession then we suggest you use the one given by the seed source and then list the others as synonyms in case it is later determined there are differences between names due to divergence or contamination."

For the "Institute Code" it would be helpful to provide this link to look them up: https://www.fao.org/wiews/data/organizations/en/?no_cache=1

For biological status of accession there seems to be a formatting issue for options 130-400 and 4.23-999 as shown in these screenshots:
![Screenshot 2023-12-12 at 1 41 41 PM](https://github.com/TripalCultivate/docs/assets/1566301/e2d7ec2b-c3fc-47aa-a14f-a8fa031b9d56)
![Screenshot 2023-12-12 at 1 45 38 PM](https://github.com/TripalCultivate/docs/assets/1566301/b32f34b9-ba0a-426c-8519-3cf0e1cd4355)

Also, it would be nice to format these in columns like shown in the following screenshot which was accomplished by adding `columns: 2;` and `column-gap: 50px;` to the `<ul>` element.
![Screenshot 2023-12-12 at 1 44 23 PM](https://github.com/TripalCultivate/docs/assets/1566301/1c2d271b-4339-4c10-9555-48f99e9fb15c)

For the "Breeding Method", I think we should expand it a bit. Since we were unable to find good guidance on what these should be (e.g. an ontology), we might want to focus more on how it is implemented in BrAPI. So something like "the short unique identifier for the method used to generate this accession. In the BrAPI, this would be the `breedingMethodDbId` and then more details for the method would be retrieved via the `/breedingmethods` call."

For the "Pedigree", you could elaborate by saying "It is recommended to use the format described in [Purdy et. al. (1969)](https://acsess.onlinelibrary.wiley.com/doi/epdf/10.2135/cropsci1968.0011183X000800040002x) (e.g. `maternal-parental\paternal-parent`)."

**Comment by carolyncaron** [comment]
Thanks for all of these suggestions! I've addressed most of them in the above commit. I am holding off on including the screenshot for now until the importer has been fully reviewed just in case there are further changes, but I definitely agree with including it!

Also, making the list formatted as columns was proving difficult for me to figure out. I've switched it to a table format for now, and I moved it to the bottom of the page to hopefully look less overwhelming. Does it look like a good solution to you, @laceysanderson?

**Comment by laceysanderson** [comment]
Found an extra little thing:

The institute code specifies where it was maintained, yet the institute name mentions where it was bred. We will want these to be consistent... I suggest switching them both to specify the institute where the material "was collected, bred or selected".

> making the list formatted as columns was proving difficult for me to figure out. I've switched it to a table format for now, and I moved it to the bottom of the page to hopefully look less overwhelming. Does it look like a good solution to you, @laceysanderson?

I think this works :-) I actually really like the colouring of the table! And by moving it outside the numbered list it breaks the flow less 👍

**Comment by carolyncaron** [comment]
> The institute code specifies where it was maintained, yet the institute name mentions where it was bred. We will want these to be consistent... I suggest switching them both to specify the institute where the material "was collected, bred or selected".

That's a good catch. It actually makes me realize that I may be confusing the difference between the External Database and the Institute. 😬 Perhaps we need to elaborate on the definitions for both of those to make it clear?

Also, I wanted to point out that there are new sections added to this page in commit https://github.com/TripalCultivate/docs/commit/95788cb83053afdfd63ad76452c18cba69f073c1. I thought it was missing a place to outline what is already expected in the database, and where to access the importer (It was previously floating below the page title).

**Comment by laceysanderson** [comment]
Closing this as it's complete and in the docs already.
